// Load the correct .env file based on NODE_ENV
const path = require('path');
const dotenv = require('dotenv');
const fs = require('fs');
const https = require('https');

const env = process.env.NODE_ENV || 'development';
dotenv.config({ path: path.resolve(__dirname, `.env.${env}`) });

const connectDB = require("./db/db");
const app = require("./app");

// Read SSL certificate and key generated by mkcert
const sslOptions = {
  key: fs.readFileSync(path.resolve(__dirname, './certs/localhost-key.pem')),
  cert: fs.readFileSync(path.resolve(__dirname, './certs/localhost.pem')),
};

connectDB()
  .then(() => {
    https.createServer(sslOptions, app).listen(process.env.PORT, () => {
      console.log(`✅ HTTPS server running in ${env} mode on https://localhost:${process.env.PORT}`);
    });
  })
  .catch((err) => {
    console.error(`❌ MongoDB connection failed: ${err}`);
  });
